server:
  port: 8080
spring:
  application:
    name: identity-service

  webflux:
    base-path: /identity

  r2dbc:
    url: "r2dbc:mysql://localhost:3306/ins_identity"
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    pool:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      connect-timeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/identity/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-name: Google
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
            redirect-uri: http://localhost:8080/identity/login/oauth2/code/facebook
            authorization-grant-type: authorization_code
            client-name: Facebook
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/identity/login/oauth2/code/github
            authorization-grant-type: authorization_code
            client-name: GitHub

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: default-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 36000


#    http://localhost:8080/identity/oauth2/authorization/google
#    http://localhost:8080/identity/oauth2/authorization/facebook
#    http://localhost:8080/identity/oauth2/authorization/github