server:
  port: 8084

spring:
  application:
    name: storage-service

  webflux:
    base-path: /storage

  r2dbc:
    url: "r2dbc:mysql://localhost:3306/ins_storage"
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    pool:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: profile-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false

  jackson:
    serialization:
      write-date-keys-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 36000

cloudinary:
  cloud-name: "dpilnbfrs"
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}